<!DOCTYPE html>
<html>
<?php 
ini_set('display_errors', 1); ini_set('display_startup_errors', 1); error_reporting(E_ALL);
?>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<body>
    <form id="form-container" method="post" action="/charge">
        <!-- Tap element will be here -->
        <div id="element-container"></div>
        <div id="error-handler" role="alert"></div>
        <div id="success" style=" display: none;;position: relative;float: left;">
            Success! Your token is <span id="token"></span>
        </div>
        <!-- Tap pay button -->
        <button id="tap-btn">Submit</button>
    </form>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js"></script>
    <script src="https://secure.gosell.io/js/sdk/tap.min.js"></script>
    <script>
        //pass your public key from tap's dashboard
        var tap =  Tapjsli('pk_test_p8xcwN9WHO0XBlQrUP72Ke5D'); //Tapjsli('pk_test_EtHFV4BuPQokJT6jiROls87Y');
        var elements = tap.elements({});
        var style = {
            base: {
                color: '#535353',
                lineHeight: '22px',
                fontFamily: 'sans-serif',
                fontSmoothing: 'antialiased',
                fontSize: '24px',
                '::placeholder': {
                    color: 'rgba(0, 0, 0, 0.26)',
                    fontSize: '20px'
                }
            },
            invalid: {
                color: 'red'
            }
        };
        // input labels/placeholders
        var labels = {
            cardNumber: "Card Number",
            expirationDate: "MM/YY",
            cvv: "CVV",
            cardHolder: "Card Holder Name"
        };
        //payment options
        var paymentOptions = {
            currencyCode: ["KWD", "USD", "SAR"],
            labels: labels,
            TextDirection: 'ltr'//'rtl'
        }
        //create element, pass style and payment options
        var card = elements.create('card', {
            style: style
        }, paymentOptions);
        //mount element
        card.mount('#element-container');
        //card change event listener
        card.addEventListener('change', function (event) {
            if (event.loaded) {
                // console.log("UI loaded :" + event.loaded);
                // console.log("current currency is :" + card.getCurrency())
            }
            var displayError = document.getElementById('error-handler');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });
        //-----------------------------------------
        // Handle form submission
        var form = document.getElementById('form-container');
        form.addEventListener('submit', function (event) {
            event.preventDefault();

            tap.createToken(card).then(function (result) {
                // console.log(result);
                console.log(result.id);

                if (result.error) {
                    // Inform the user if there was an error
                    var errorElement = document.getElementById('error-handler');
                    errorElement.textContent = result.error.message;
                } else {
                    // Send the token to your server
                    var errorElement = document.getElementById('success');
                    errorElement.style.display = "block";
                    var tokenElement = document.getElementById('token');
                    tokenElement.textContent = result.id;
                    console.log(token);
                    insertToken(result.id);
                    tapTokenHandler(token)

                }
            });
        });
        //-----------------------
        function tapTokenHandler(token) {
            // Insert the token ID into the form so it gets submitted to the server
            var form = document.getElementById('payment-form');
            var hiddenInput = document.createElement('input');
            hiddenInput.setAttribute('type', 'hidden');
            hiddenInput.setAttribute('name', 'tapToken');
            hiddenInput.setAttribute('value', token.id);
            form.appendChild(hiddenInput);

            // Submit the form
            form.submit();
        }
        //-------------------------------
        card.addEventListener('change', function (event) {
            if (event.BIN) {
                // console.log(event.BIN)
            }
            var displayError = document.getElementById('card-errors');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });
        function insertToken(token){
            console.log(token);
            $.ajax({
                type: "GET",
                url: '<?php echo $this->escape($this->url(array(), 'inserttoken'))."?forAjax=true"; ?>',
                data: {'token_id': 151,'card_id': "ask"},
                dataType: "json",
                success: function (response) {
                    console.log("done");
                }
            });
        }
        
    </script>
</body>

</html>